DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS PERSONAL_DETAIL_DATA;
DROP TABLE IF EXISTS EMPLOYEE_DATA;



CREATE TABLE EMPLOYEE (
  employee_id VARCHAR(250) PRIMARY KEY,
  name VARCHAR(250),
  email VARCHAR(250),
  salary VARCHAR(250)
);

--CREATE TABLE PERSONAL_DETAIL_DATA (
--  employee_id VARCHAR(250) PRIMARY KEY,
--  name VARCHAR(250),
--  email VARCHAR(250),
--  idNumber VARCHAR(250)
--);
--
--
--CREATE TABLE EMPLOYEE_DATA (
--  sno VARCHAR(250) PRIMARY KEY,
--  employee_id VARCHAR(250)
--);
--
--alter table EMPLOYEE_DATA add CONSTRAINT fk_emppersonal
--    FOREIGN KEY (employee_id)
--    REFERENCES PERSONAL_DETAIL_DATA(employee_id);